---
- name: Deploy and test Kubernetes cluster with k3s, Nginx, HPA, monitoring and k6 load test
  hosts: all
  remote_user: root
  become: true
  gather_facts: true
  roles:
    - { role: roles/k3s }
