apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
              requests:
                cpu: "25m"
                memory: "30Mi"
              limits:
                cpu: "40m"
                memory: "50Mi"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf  
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config